name: Security Audit
on:
  schedule:
    # runs every Friday at 12 AM
    - cron: '0 0 * * 5'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}